# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Admin Web Build2

on:
  push:
    branches: 
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Set up Node.js ${{ matrix.node-verison }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-verison }}
      - uses: actions/checkout@master
      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
